### ISSUE TITLE
1_MoveCol.ts breaks when encountering friendly mines

### ISSUE THREAD

**Issue by mhrivnak** [TW2002/twxp#50]
https://github.com/MicroBlaster/TWXProxy/wiki/1_MoveCol.ts

If moving colonists from 101 > 102 > 103 without a t-warp drive, and if there are friendly mines in 102, then the script breaks. It seems that even though it selects express mode, the presence of mines causes the prompt "Stop in this sector?" anyway, which the script doesn't expect and can't handle.

This is of course annoying since it's common to have mines in a base, and common to move colonists around within a base.

`Trade Wars 2002 ver 3.34b Gold`

**Comment by DMC73120** [comment]
I am not really a scripter, but I think mombot has a script that will do what you want. This script was writter by Xide 20+ years ago.

Please join us on discord:

TWX Proxy Channel - https://discord.com/channels/616468546452717568/717135837082550383

Mombot Channel - https://discord.com/channels/544098315881545728/556906508437160101

Since this is not a problem with TWXP.exe I am going to close this issue.
